backend/account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('register/', views.Register.as_view(), name='register'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('dashboard/<str:username>/', views.Dashboard.as_view(), name='dashboard'),
]

backend/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('account/', include('account.urls', namespace='account')),
]

backend/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('bucket/', views.Bucket.as_view(), name='bkt-home'),
    path('bucket-delete/<str:name>/', views.BucketDeleteObject.as_view(), name='bkt-del-obj'),
    path('bucket-download/<str:name>/', views.BucketDownloadObject.as_view(), name='bkt-dow-obj'),
]

backend/account/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='1.jpg')

    def __str__(self):
        return self.user.username


def save_profile(sender, **kwargs):
    if kwargs['created']:
        Profile.objects.create(user=kwargs['instance'])


post_save.connect(save_profile, sender=User)

backend/core/models.py
from django.db import models

# Create your models here.

backend/account/forms.py
from django import forms
from .models import Profile


class UserRegistrationForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class UserLoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class ProfileImageForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('image',)

backend/account/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from .forms import UserRegistrationForm, UserLoginForm, ProfileImageForm
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages


class Register(View):
    form_class = UserRegistrationForm
    template_name = 'account/register.html'

    def get(self, request):
        form = self.form_class
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            User.objects.create_user(cd['username'], cd['email'], cd['password'])
            messages.success(request, 'you register successfully', 'success')
            return redirect('core:home')
        else:
            messages.warning(request, 'you full input allright', 'warning')
            return render(request, self.template_name, {'form': form})


class Login(View):
    form_calss = UserLoginForm
    template_name = 'account/login.html'

    def get(self, request):
        form = self.form_calss
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_calss(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd['username'], password=cd['password'])
            if user is not None:
                login(request, user)
                messages.success(request, 'your Login success', 'success')
                return redirect('core:home')
            else:
                messages.warning(request, 'your pass or username is not corect')
                return render(request, self.template_name, {'form': form})
        else:
            messages.warning(request, 'your pass or username is not corect')
            return render(request, self.template_name, {'form': form})


class Logout(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        messages.success(request, 'your logout success', 'success')
        return redirect('core:home')


class Dashboard(LoginRequiredMixin, View):
    form_class = ProfileImageForm
    template_name = 'account/dashboard.html'

    def get(self, request, username):
        user = get_object_or_404(User, username=username)
        return render(request, self.template_name, {'user': user, 'form': self.form_class})

    def post(self, request, *args, **kwargs):
        form = ProfileImageForm(request.POST, request.FILES, instance=request.user.profile)
        if form.is_valid():
            form.save()
            messages.success(request, 'your image uploaded', 'info')
            return redirect('account:dashboard', request.user.username)
        else:
            messages.warning(request, 'dont image uploaded', 'warning')
            return redirect('account:dashboard', request.user.username)

backend/core/views.py
from django.shortcuts import render, redirect
from django.views import View
from . import tasks
from django.contrib import messages


class Home(View):
    def get(self, request):
        return render(request, 'core/home.html')


class Bucket(View):
    template_name = 'core/bucket.html'

    def get(self, request):
        objects = tasks.all_bucket_objects_task()
        return render(request, self.template_name, {'objects': objects})


class BucketDeleteObject(View):
    def get(self, request, name):
        tasks.delete_bucket_objetc_task.delay(name)
        messages.success(request, f'"{name}" deleted success', 'info')
        return redirect('core:bkt-home')


class BucketDownloadObject(View):
    def get(self, request, name):
        tasks.download_bucket_object_task.delay(name)
        messages.success(request, f'"{name}" download success', 'info')
        return redirect('core:bkt-home')

backend/core/templates/core/bucket.html
{% extends 'base.html' %}
{% block content %}
<table class="table table-dark rounded">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Size</th>
        <th scope="col">Download</th>
        <th scope="col">Delete</th>
    </tr>
    </thead>
    <tbody>
    {% for obj in objects %}
    <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{obj.Key}}</td>
        <td>{{obj.Size|filesizeformat}}</td>
        <td><a href="{% url 'core:bkt-dow-obj' obj.Key %}">Download</a></td>
        <td><a href="{% url 'core:bkt-del-obj' obj.Key %}">Delete</a></td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

backend/core/templates/core/home.html
{% extends 'base.html'%}


{% block content %}
<h3>Home</h3>
{% endblock %}

backend/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
</head>
<body>

{% include 'inc/navbar.html' %}
<div class="jumbotron">
    {% include 'inc/messages.html' %}
    {% block content %} {% endblock %}
</div>

</body>
</html>

backend/templates/inc/messages.html
{% if messages %}
    {% for message in messages %}
        <p class="alert alert-{{message.tags}}">{{ message}}</p>
    {% endfor %}
{% endif %}

backend/templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="navbar-nav">
        <a class="nav-link active" href="{% url 'core:home' %}">Home</a>
        {% if request.user.is_authenticated %}
        <a class="nav-link active" href="{% url 'account:logout' %}">Logout</a>
        <a class="nav-link active" href="{% url 'account:dashboard' request.user.username %}">Dashboard</a>
        {% else %}
        <a class="nav-link active" href="{% url 'account:register' %}">Register</a>
        <a class="nav-link active" href="{% url 'account:login' %}">Login</a>
        {% endif %}
        {% if request.user.is_superuser %}
        <a class="nav-link active" href="{% url 'core:bkt-home' %}">Bucket</a>
        {% endif %}
    </div>
</nav>